# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job2:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-files.outputs.modified_folders }}
      json_result: ${{ steps.changed-files.outputs.json_result }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install Python Library
        run: |
          pip install fire
      - name: Run Python scripts
        id: changed-files
        run: |
            if ${{ github.event_name == 'pull_request' }}; then
                modified_files=$(git diff --name-only -r HEAD^1 HEAD | xargs)
            else
                modified_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)
            fi
            result=$(python .github/workflows/test.py $modified_files)
            echo "$(python .github/workflows/test.py --modified-files=$modified_files)"
            echo "json_result: $result"
            echo "json_result=$result" >> $GITHUB_OUTPUT
      - name: Temp
        run: |
            echo ${{ steps.changed-files.outputs.json_result }}  
  matrix-job:
    needs: job2
    runs-on: ubuntu-latest
    strategy:
      matrix:
        item: ${{ fromJson(needs.job2.outputs.json_result) }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Process matrix item
        run: |
          echo "Processing item: ${{matrix.item}}"
